### PR TITLE
SCTP rewrite

### PR DESCRIPTION
**Pull request by sipsorcery**
Improve data channel support.

### CODE REVIEW

**Comment by sipsorcery** [comment]
@Terricide this PR is not yet finished (probably about 60-70% done) but the a lot of the required SCTP plumbing is in place. Opening and closing data channels, as well as unordered sends that don't require fragmentation, are working well.

I've taken the changes you made to the stress test program and added them to this PR. The test now seems to work well with this PR (just don't set the `dataSize` above about `800` to keep the SCTP packet size below the MTU). If you have any other tests you need to run on the data channels it would be useful for me.

**Comment by Terricide** [comment]
@sipsorcery cool, I'll take a look, if I find things to fix should I do a PR, or should I wait a bit longer?

**Comment by sipsorcery** [comment]
No need for fixes at this point, still got a way to go before it's ready. If you have any existing tests you run they would be useful.

**Comment by Terricide** [comment]
Honestly I don't have any tests I just have my applications that use the library in a few different ways.

**Comment by sipsorcery** [comment]
OK, no worries. Hopefully the PR should be finished sometime this week.

**Comment by Terricide** [comment]
Cool Ill start some testing monday

**Comment by Terricide** [comment]
FYI it is looking pretty good in my testing so far.

**Pull request merged**
