### PR TITLE
New fix for SRTP in SIP calls with multiple media types

### PR DESCRIPTION
**Pull request by Cheroukee**
This is a new attempt at fixing SRTP in SIP calls with more than one media type.
This fix does not break WebRTC video. 

The changes between the previous PR and this on is that we only decrypt the incoming video packets if possible and do not skip a packet due to the ssrc not being set. 

The video part would not initialize the frame decoder correctly if the first packet was skipped entirely

Tested the WebRTCReceiver/WebRTCReceiver/WebRTCMp4Source projects

Tested with SIP calls with different combos of audio only/audio and video (with or without the secure part)

### CODE REVIEW

**Comment by Cheroukee** [comment]
This would fix #648

**Comment by sipsorcery** [comment]
Thanks for the fix. The `WebRTCReceiver` example is now working for me.

@ChristopheI are you able to test this PR to see if it fixes the problem you encountered on #660?

**Comment by ChristopheI** [comment]
I will test it on Tuesday.

**Comment by ChristopheI** [comment]
@sipsorcery I successfully tested this PR.

**Comment by Cheroukee** [comment]
Sorry for taking a while to comeback to you ! 

I'd like to understand better the mutiple video streams : you mean having video1 and video2 coming at once instead of only a single one at a time ?

For your remarks : 

- RTCPeerConnection.IsDtlsNegotiationComplete : I think this was left for the sake of backwards compatibility/not breaking consumers that would use it
- Depending on how the SDP is negotiated and what the context is, I would say yes with a 90% chance. If this is for SIP, from my experience with it, video and audio each have their own set of crypto descriptions. They are not multiplexed on the same channel. For WebRTC, they were actually all on the same channel, which explains your next question. 
- Because all of the media types were on the same channel, I had to set the single security context to all of the media types. In SIP, they come from different channels therefore they have their unique Security Context per media type.

**Comment by ChristopheI** [comment]
Thanks a lot to take time to answer me.

> I'd like to understand better the mutiple video streams : you mean having video1 and video2 coming at once instead of only a single one at a time ?

Yes, several video stream in same time: for example a webcam and a desktop sharing.  I'm currently working on this task (see #711)

Do you have time to check if I correctly manage it in this PR ?  (not totally finished yet but already testable)

I can easily test in WebRTC context but not really in SIP context. 

Thx

**Pull request merged**
