### PR TITLE
Updated getting authenticated STUN request to use FIPS compliant library.

### PR DESCRIPTION
**Pull request by pabi-milestone**
Resolves #1236.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Does this fix the FIPS non-compliance? I thought that was caused by any use of the MD5 hash?

**Review by sipsorcery — APPROVED** [review]

**Comment by pabi-milestone** [comment]
> Does this fix the FIPS non-compliance? I thought that was caused by any use of the MD5 hash?

I’m sorry, the title of the pull request was misleading. You are right that it doesn’t fix non-compliance, but it does allow the code to run on Windows with FIPS enabled

**Comment by pabi-milestone** [comment]
@sipsorcery We have discussed this issue with our security and compliance department, and they have determined that using MD5 for hashing to support digest authentication is allowed in combination with FIPS-2. Regarding FIPS-3, their initial assessment is that it should still be allowed; however, this is something they will be looking into more next year.

**Comment by sipsorcery** [comment]
@pabi-milestone sounds like a pragmatic approach. It's not a trivial matter to get the Internet to update to a new standard overnight 😉.

**Pull request merged**
