### PR TITLE
Synchronize call answer and end methods

### PR DESCRIPTION
**Pull request by kuleshov-aleksei**
Hello! This PR is connected with issue https://github.com/sipsorcery-org/sipsorcery/issues/818

There can be two race-conditions both occurs when call is being answered and CANCELLed at the same time. For example:
Application receives SIP INVITE, answer with  
INVITE 100 Trying  
INVITE 180 Ringing  

but does not send INVITE 200 Ok right away (this is our use-case)

while client becomes ready to fully answer call, telephony server sends CANCEL command. In rare occasions it can lead to observed or unobserved exceptions.

If call answered before CANCEL (but still at the same time), there will be this message at Error level:

```
Exception SIPMessageReceived. Object reference not set to an instance of an object.
BadRequest Received udp:localip:54533<-udp:asteriskip:5060: message - Exception SIPTransport. Object reference not set to an instance of an object., field - Unknown, rawMessage - CANCEL sip:alice@localip:54533 SIP/2.0
Via: SIP/2.0/UDP asteriskip:5060;branch=z9hG4bK2d0ec7c0
Max-Forwards: 70
From: <sip:bob@asteriskip>;tag=as0ca8d21b
To: <sip:alice@localip:54533>
Call-ID: cbd46055c9474853903260fac59b0635@asteriskip:5060
CSeq: 102 CANCEL
User-Agent: Asterisk PBX 13.27.0
Content-Length: 0
```

If call cancelled just before answer, there will be UnobservedTaskException leading to shutdown of whole application:
```
Processing HandleFatalException for AggregateException (from TaskScheduler_UnobservedTaskException) Object reference not set to an instance of an object. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SIPSorcery.SIP.App.SIPUserAgent.SIPTransportRequestReceived(SIPEndPoint localSIPEndPoint, SIPEndPoint remoteEndPoint, SIPRequest sipRequest) in /_/src/app/SIPUserAgents/SIPUserAgent.cs:line 1369
```

(yeah, stack trace is not informative in this case)

This PR attempts to synchronize `Answer()` and `CallEnded()` methods using lightweight semaphore (lock cannot be used because `Answer()` is async). I've wrapped this methods in `try ... finally ...` block. Feel free to mention in case if this approach is not suitable here.

As I noticed, these methods are only one that can change value of `MediaSession` and `m_sipDialogue` inside `SIPUserAgent` class (at the same time), so I hope this will be enough.

I am open to discussion if you have better solution

<details>
<summary>A bit of logs for context:</summary>
<br>
<pre>
2022-09-13 14:41:04.8635 [sipsorcery          :Info] Incoming call request: udp:localip:54533<-udp:asteriskip:5060, uri:sip:alice@localip:54533. 
2022-09-13 14:41:04.8638 [sipsorcery          :Debug] UAS call progressing with Trying. 
2022-09-13 14:41:04.8638 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) changed: Transaction send info response (is reliable False) INVITE 100 Trying 
2022-09-13 14:41:04.8639 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) state changed: (InviteServer) - Trying 
2022-09-13 14:41:04.8639 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) changed: Transaction state changed to Trying. 
2022-09-13 14:41:04.8639 [SipTransportProvider:Trace] Response Sent udp:localip:54533->udp:asteriskip:5060: INVITE 100 Trying. 
2022-09-13 14:41:04.8639 [sipsorcery          :Debug] UAS call progressing with Ringing. 
2022-09-13 14:41:04.8640 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) changed: Transaction send info response (is reliable False) INVITE 180 Ringing 
2022-09-13 14:41:04.8640 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) state changed: (InviteServer) - Proceeding 
2022-09-13 14:41:04.8640 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) changed: Transaction state changed to Proceeding. 
2022-09-13 14:41:04.8640 [SipTransportProvider:Trace] Response Sent udp:localip:54533->udp:asteriskip:5060: INVITE 180 Ringing. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] CreateRtpSocket attempting to create and bind RTP socket(s) on localip:0. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on localip:12530. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] CreateBoundUdpSocket successfully bound on localip:12530. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on localip:12531. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] CreateBoundUdpSocket successfully bound on localip:12531. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] Successfully bound RTP socket localip:12530 and control socket localip:12531. 
2022-09-13 14:41:04.8642 [sipsorcery          :Debug] RTPChannel for localip:12530 started. 
...
2022-09-13 14:41:04.8771 [SipTransportProvider:Trace] Request Received udp:localip:54533<-udp:asteriskip:5060: CANCEL sip:alice@localip:54533 SIP/2.0. 
2022-09-13 14:41:04.8775 [sipsorcery          :Debug] Setting audio sink and source format to 8:PCMA 8000 (RTP clock rate 8000). 
2022-09-13 14:41:04.8775 [sipsorcery          :Debug] SIPServerUserAgent got cancellation request. 
2022-09-13 14:41:04.8777 [sipsorcery          :Error] Exception SIPMessageReceived. Object reference not set to an instance of an object. 
2022-09-13 14:41:04.8859 [SipTransportProvider:Trace] BadRequest Received udp:localip:54533<-udp:asteriskip:5060: message - Exception SIPTransport. Object reference not set to an instance of an object., field - Unknown, rawMessage - CANCEL sip:alice@localip:54533 SIP/2.0
Via: SIP/2.0/UDP asteriskip:5060;branch=z9hG4bK2d0ec7c0
Max-Forwards: 70
From: <sip:bob@asteriskip>;tag=as0ca8d21b
To: <sip:alice@localip:54533>
Call-ID: cbd46055c9474853903260fac59b0635@asteriskip:5060
CSeq: 102 CANCEL
User-Agent: Asterisk PBX 13.27.0
Content-Length: 0
2022-09-13 14:41:04.9141 [SipTransportProvider:Trace] Response Sent udp:localip:54533->udp:asteriskip:5060: INVITE 200 Ok. 
2022-09-13 14:41:04.9145 [SipTransportProvider:Trace] Request Received udp:localip:54533<-udp:asteriskip:5060: ACK sip:localip:54533 SIP/2.0. 
2022-09-13 14:41:04.9145 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) state changed: (InviteServer) - Confirmed 
2022-09-13 14:41:04.9145 [SipClient           :Trace] Transaction (branchId: z9hG4bK2d0ec7c0, transactionId: v2C49a4gYMd2t7rJpbhSmkYVHM4=) changed: Transaction state changed to Confirmed. 
2022-09-13 14:41:04.9146 [SipTransportProvider:Trace] Request Received udp:localip:54533<-udp:asteriskip:5060: BYE sip:localip:54533 SIP/2.0. 
</pre></details>

### CODE REVIEW

**Comment by sipsorcery** [comment]
Nice fix, thanks.

**Comment by alexavator** [comment]
There is a deadlock because of this fix. I subscribed to HangUp event, and when it raised my code called userAgent.Dispose method. 

So, CallEnded lock semaphore and fire HangUp event. It would not release semaphore until HangUp finished. My code got HangUp event and call Dispose, which wait for the same semaphore. Here is a deadlock. 

Is it really nessecary to wait the semaphore at dispose?

**Comment by alexavator** [comment]
oh, I see, we will get an ObjectDisposedException if we won`t wait...

**Comment by happyDDD** [comment]
should also do the same on ClientCallAnsweredHandler

**Pull request merged**
