### PR TITLE
Fix SIP/TLS RINGING not sent after TRYING (#889)

### PR DESCRIPTION
**Pull request by steffen-liersch**
The workaround has been proven to work in production.

When using SIP/TLS on an incoming call, RINGING after TRYING may not be sent over the network. Instead, the following exception occurs:

```
System.NotSupportedException: The BeginWrite method cannot be called when another write operation is pending.
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at SIPSorcery.SIP.SIPTLSChannel.SendOnConnected(SIPStreamConnection sipStreamConn, Byte[] buffer)
   at SIPSorcery.SIP.SIPTCPChannel.SendSecureAsync(SIPEndPoint dstSIPEndPoint, Byte[] buffer, String serverCertificateName, Boolean
```

### CODE REVIEW

**Comment by sipsorcery** [comment]
This won't work properly as all the calls to SendOnConnected are expecting a non-blocking call. Changing to blocking is a fundamental difference.

**Comment by steffen-liersch** [comment]
It is clear that the non-blocking function is now blocking. That is why my suggestion is only a workaround.

I am in the process of working out a correction. With the help of my correction there will then be a function `WriteAsync` that is thread-safe and no longer causes the described error.

I will test the changes extensively first before updating the pull request here. I ask for some more patience.

**Comment by sipsorcery** [comment]
@steffen-liersch  what about the approach below from ChatGPT? It's similar to yours but the `SslStreamWriter` is more obvious in its intent than `SslStreamWrapper`.

```
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

public class SslStreamWriter
{
    private readonly Queue<byte[]> writeQueue = new Queue<byte[]>();
    private readonly object lockObject = new object();
    private readonly TaskCompletionSource<bool> completionSource = new TaskCompletionSource<bool>();
    private readonly ManualResetEventSlim writeEvent = new ManualResetEventSlim(false);
    private readonly CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
    private readonly Task writeTask;

    public SslStreamWriter(SslStream sslStream)
    {
        writeTask = Task.Run(async () =>
        {
            while (!cancellationTokenSource.IsCancellationRequested)
            {
                writeEvent.Wait(cancellationTokenSource.Token);

                byte[] buffer;

                lock (lockObject)
                {
                    if (writeQueue.Count == 0)
                    {
                        continue;
                    }

                    buffer = writeQueue.Dequeue();
                }

                try
                {
                    await sslStream.WriteAsync(buffer, 0, buffer.Length, cancellationTokenSource.Token);
                }
                catch (Exception ex)
                {
                    completionSource.TrySetException(ex);
                    return;
                }
            }
        }, cancellationTokenSource.Token);
    }

    public Task WriteAsync(byte[] buffer)
    {
        lock (lockObject)
        {
            writeQueue.Enqueue(buffer);
        }

        writeEvent.Set();
        return completionSource.Task;
    }

    public void Cancel()
    {
        cancellationTokenSource.Cancel();
    }
}
```

Explanation:

> In this updated example, the background task uses the ManualResetEventSlim object to wait for new writes to process. The Set method is called on the event object when a new write is added to the queue, which signals the background task to start processing the writes.

> The Cancel method cancels the background task when it's no longer needed. This is important to avoid leaking resources when the SslStreamWriter object is no longer needed.

> This approach ensures that the background task only runs when there are pending writes in the queue, which can help reduce resource usage and improve performance.

And then in `SIPStreamConnection` make `SslStream` private and use your Read methods and for write:

```
SslStreamWriter _writer =  new SslStreamWriter(SslStream);

await _writer.WriteAsync(buffer);
```

**Comment by steffen-liersch** [comment]
The ChatGPT variant is actually easier to understand. However, `writeEvent.Wait(cancellationTokenSource.Token)` occupies the thread for the entire duration. In my opinion, this reduces the number of available threads in the thread pool. Therefore, I would prefer my variant, as it is completely based on the async-await mechanisms. Moreover, there are already positive test results from our customers.

**Pull request merged**
