### PR TITLE
Fixes the construction of PRACK requests

### LINKED ISSUE #414: telekom.de interop - RequestUri for PRACK & Eearly Media
Hi,

I am trying to use sipsorcery to connect to a SIP Trunk provided by the German telecom provider telekom.de. After some trial and error and comparing wireshark-traces from PhonerLite I got basic incomming and outgoing calls to work. I needed to "fix" sipsorcery in two ways however:

First, telekom.de needs to have the RequestURI updated to whatever Contact-Uri it sends back in a 183 Session Progress response for the PRACK. If this is not updated, telekom.de responds with `SIP/2.0 503 Service Unavailable (R503_ALL_SYSTEMS_UNRESPONSIVE)` and no call is established.
I fixed this by copying the code from `UACInviteTransaction.Get2xxAckRequest()` which deals with adjusting RequestUri from the Contact to `UACInviteTransaction.GetPRackRequest()`, which fixed the problem and allowed for proper call establishment. https://github.com/tstaehli/sipsorcery/commit/7acff821e56468750091a4781e8509751a4f96a4

Second, telekom.de sends the SDP in a 183 and does not send an SDP in the 200 OK Respnse to the INVITE. This caused an exception "The session description cannot be null for SetRemoteDescription", so I tried to fix this: https://github.com/tstaehli/sipsorcery/commit/643184907af83e761bbd3af2fc5ca6de0e55c59a

I tried to find the relevant section in the SIP RFC which deals with when the Reuqets URI needs to be adjusted but did not find it. I actually think that there is a problem in the SIP-Stack/Infrastructure of telekom.de, because the Contact they send is really cryptic and clearly internal. For example: `Contact: <sip:n+afFG245FSFF434+THgsd346FDER43HNy5GOc35q/m@th1>`

What is your preferred way for integrating patches? 
Should I just submit a Pull Request and we can continue discussion there on details?
For the first problem, maybe there needs to be some kind of switch to avoid breaking other SIP-Trunk providers?

Please let me know, if you need any further information.

Regards,
Tobias

### PR DESCRIPTION
**Pull request by sipsorcery**
@tstaehli this should fix #414.

If it's feasible can you try put this PR to see it solves the signaling with telekom.de.

### CODE REVIEW

**Comment by tstaehli** [comment]
I just tried it; there seems to be a problem. This is not ready to merge!

the ACK is sent again and again: I will try to narrow it down a bit more tomorrow, for today i am out of time.

**Comment by sipsorcery** [comment]
Sure, no problem. The merge can wait until you can confirm it's fixed.

**Comment by sipsorcery** [comment]
Added additional change. I was setting the CSeq value on the `ACK` header incorrectly.

Looks good now, although I haven't set things up to replicate the `Record-Route` header on the `PRACK` which is what you need for telekom.de.

````
<--- Received SIP request (687 bytes) from UDP:192.168.0.50:54617 --->
INVITE sip:105@192.168.0.48 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.50:54617;branch=z9hG4bK17580bf85e6445ce841f85f55ffb5cea;rport
To: <sip:105@192.168.0.48:5060>
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
Call-ID: 33cbfb9035d146b587ed8ca64a102862
CSeq: 1 INVITE
Contact: <sip:Anonymous@192.168.0.50:54617>
Max-Forwards: 70
User-Agent: sipsorcery_v5.0.18.0
Supported: replaces, norefersub, 100rel
Content-Length: 223
Content-Type: application/sdp

v=0
o=- 1909025224 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 192.168.0.50
t=0 0
m=audio 54614 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv

<--- Transmitting SIP response (329 bytes) to UDP:192.168.0.50:54617 --->
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.0.50:54617;rport=54617;received=192.168.0.50;branch=z9hG4bK17580bf85e6445ce841f85f55ffb5cea
Call-ID: 33cbfb9035d146b587ed8ca64a102862
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
To: <sip:105@192.168.0.48>
CSeq: 1 INVITE
Server: Asterisk PBX 18.2.0
Content-Length:  0


    -- Executing [105@from-internal:1] Progress("PJSIP/6001-0000000c", "") in new stack
    -- Executing [105@from-internal:2] Wait("PJSIP/6001-0000000c", "1") in new stack
<--- Transmitting SIP response (841 bytes) to UDP:192.168.0.50:54617 --->
SIP/2.0 183 Session Progress
Via: SIP/2.0/UDP 192.168.0.50:54617;rport=54617;received=192.168.0.50;branch=z9hG4bK17580bf85e6445ce841f85f55ffb5cea
Call-ID: 33cbfb9035d146b587ed8ca64a102862
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
To: <sip:105@192.168.0.48>;tag=261c6acd-ab81-4819-b77c-81c0cd95f963
CSeq: 1 INVITE
Server: Asterisk PBX 18.2.0
Contact: <sip:192.168.0.48:5060>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Require: 100rel
RSeq: 11601
Content-Type: application/sdp
Content-Length:   252

v=0
o=- 1909025224 2 IN IP4 192.168.0.48
s=Asterisk
c=IN IP4 192.168.0.48
t=0 0
m=audio 11734 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

<--- Received SIP request (368 bytes) from UDP:192.168.0.50:54617 --->
PRACK sip:192.168.0.48:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.50:54617;branch=z9hG4bKf6c28687733742db8e673b914613b3c9;rport
To: <sip:105@192.168.0.48>;tag=261c6acd-ab81-4819-b77c-81c0cd95f963
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
Call-ID: 33cbfb9035d146b587ed8ca64a102862
CSeq: 2 PRACK
Max-Forwards: 70
Content-Length: 0
RAck: 11601 1 INVITE


<--- Transmitting SIP response (365 bytes) to UDP:192.168.0.50:54617 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.50:54617;rport=54617;received=192.168.0.50;branch=z9hG4bKf6c28687733742db8e673b914613b3c9
Call-ID: 33cbfb9035d146b587ed8ca64a102862
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
To: <sip:105@192.168.0.48>;tag=261c6acd-ab81-4819-b77c-81c0cd95f963
CSeq: 2 PRACK
Server: Asterisk PBX 18.2.0
Content-Length:  0


    -- Executing [105@from-internal:3] Answer("PJSIP/6001-0000000c", "") in new stack
<--- Transmitting SIP response (559 bytes) to UDP:192.168.0.50:54617 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.50:54617;rport=54617;received=192.168.0.50;branch=z9hG4bK17580bf85e6445ce841f85f55ffb5cea
Call-ID: 33cbfb9035d146b587ed8ca64a102862
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
To: <sip:105@192.168.0.48>;tag=261c6acd-ab81-4819-b77c-81c0cd95f963
CSeq: 1 INVITE
Server: Asterisk PBX 18.2.0
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Contact: <sip:192.168.0.48:5060>
Supported: 100rel, timer, replaces, norefersub
Content-Length:  0


    -- Executing [105@from-internal:4] MusicOnHold("PJSIP/6001-0000000c", "") in new stack
    -- Started music on hold, class 'default', on channel 'PJSIP/6001-0000000c'
<--- Received SIP request (342 bytes) from UDP:192.168.0.50:54617 --->
ACK sip:192.168.0.48:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.50:54617;branch=z9hG4bK206bc24033394944bf0fbd42217e0d26;rport
To: <sip:105@192.168.0.48>;tag=261c6acd-ab81-4819-b77c-81c0cd95f963
From: <sip:thisis@anonymous.invalid>;tag=MREUEBQFSW
Call-ID: 33cbfb9035d146b587ed8ca64a102862
CSeq: 1 ACK
Max-Forwards: 70
Content-Length: 0


asterisk*CLI>
````

**Comment by tstaehli** [comment]
I just tested this with telekom.de; it works now :-) 
Thank you for your quick response and your help in fixing this.

**Pull request merged**
